<?php
/**
 * Created by PhpStorm.
 * User: Narbe
 * Date: 05.01.2018
 * Time: 12:31
 */

class Narbe_Questreport_Block_Adminhtml_Questreport_Grid extends Mage_Adminhtml_Block_Widget_Grid
{
    public function __construct()
    {
        parent::__construct();
        $this->setId('questreportGrid');
        $this->setDefaultSort('id_questreport');
        $this->setDefaultDir('ASC');
        $this->setSaveParametersInSession(true);
    }

    protected function _prepareCollection()
    {
        $collection = Mage::getModel('questreport/questreport')->getCollection();
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
        return parent::_prepareCollection();
    }

    protected function _prepareColumns()
    {
        $this->addColumn('id_questreport', array(
            'header'    => Mage::helper('questreport')->__('ID'),
            'align'     => 'right',
            'width'     => '50px',
            'index'     => 'id_questreport',
        ));

        $this->addColumn('client_ip', array(
            'header'    => Mage::helper('questreport')->__('IP Klienta'),
            'align'     => 'left',
            'index'     => 'client_ip'
        ));

        $this->addColumn('product_id', array(
            'header'    => Mage::helper('questreport')->__('ID Produktu'),
            'align'     => 'left',
            'index'     => 'product_id'
        ));
        $this->addColumn('timestamp', array(
            'header'    => Mage::helper('questreport')->__('Data odwiedzin'),
            'align'     => 'left',
            'index'     => 'timestamp'
        ));

        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }

    public function getRowUrl($item)
    {
//        return parent::getRowUrl($item); // TODO: Change the autogenerated stub
    }
}
