<?php
/**
 * Created by PhpStorm.
 * User: Narbe
 * Date: 05.01.2018
 * Time: 12:25
 */

class Narbe_Questreport_Model_Mysql4_Questreport_Collection extends Mage_Core_Model_Mysql4_Collection_Abstract
{
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('questreport/questreport');
    }
}